sudo: false
dist: trusty
language: python
# cache:
#   apt: true
#   pip: true
#   directories:
#   - $HOME/caffe2

python:
  - "2.7"
  - "3.6"

env:
  - CHAINER_VERSION="==3.2.0" ONNX_VERSION="==1.0.0" ONNX_CAFFE2_VERSION="==1.0.0"
  - CHAINER_VERSION="==4.0.0b2" ONNX_VERSION="==1.0.0" ONNX_CAFFE2_VERSION="==1.0.0"

notifications:
  email: false

addons:
  apt:
    packages:
      - build-essential
      - curl
      - git

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      curl -L https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh -o $HOME/miniconda.sh;
      PYTHON_VER="2.7";
    else
      curl -L https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -o $HOME/miniconda.sh;
      PYTHON_VER="3.6m";
    fi
  - cd $HOME && bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME/miniconda/lib:$LD_LIBRARY_PATH"
  - export LIBRARY_PATH="$HOME/miniconda/lib:$LIBRARY_PATH"
  - export CPATH="$HOME/miniconda/include:$CPATH"
  - export CPATH="$HOME/miniconda/include/python$PYTHON_VER:$CPATH"
  - ls $HOME/miniconda/include/python$PYTHON_VER
  - printenv
  - conda config --set always_yes yes --set changeps1 no
  - conda install -c conda-forge protobuf
  - conda install -c conda-forge numpy
  - conda install -c conda-forge cmake
  - pip install "onnx$ONNX_VERSION"
  - pip install future
  - pip install hypothesis
  - pip install flake8
  - pip install hacking
  - pip install autopep8
  - pip install mock
  - pip install pytest
  - pip install six
  - pip install "chainer$CHAINER_VERSION"
  - hash -r
  - if [ ! -d $HOME/caffe2 ]; then
      git clone --recursive https://github.com/caffe2/caffe2.git $HOME/caffe2;
    fi
  - if [ ! -d $HOME/caffe2/build ]; then
      mkdir -p $HOME/caffe2/build;
    fi
  - ls $HOME/miniconda/lib
  - if [ ! -d $HOME/caffe2/install ]; then
      cd $HOME/caffe2/build && cmake ..
      -DUSE_CUDA=OFF
      -DUSE_NCCL=OFF
      -DUSE_NNPACK=OFF
      -DUSE_ROCKSDB=OFF
      -DUSE_LEVELDB=OFF
      -DUSE_LMDB=OFF
      -DUSE_OPENCV=OFF
      -DBUILD_TEST=OFF
      -DBUILD_BENCHMARK=OFF
      -DCMAKE_INSTALL_PREFIX=../install
      -DPYTHON_EXECUTABLE=$HOME/miniconda/bin/python
      -DPYTHON_INCLUDE_DIR=$HOME/miniconda/include
      -DPYTHON_INCLUDE_DIR2=$HOME/miniconda/include/python$PYTHON_VER
      -DPYTHON_LIBRARY=$HOME/miniconda/lib/libpython$PYTHON_VER.so
      -DPYTHON_LIBRARY_DEBUG=$HOME/miniconda/lib/libpython$PYTHON_VER.so
      -DPROTOBUF_INCLUDE_DIR=$HOME/miniconda/include
      -DPROTOBUF_LIBRARY=$HOME/miniconda/lib/libprotobuf.so
      -DPROTOBUF_LIBRARY_DEBUG=$HOME/miniconda/lib/libprotobuf.so
      -DPROTOBUF_LITE_LIBRARY=$HOME/miniconda/lib/libprotobuf-lite.so
      -DPROTOBUF_LITE_LIBRARY_DEBUG=$HOME/miniconda/lib/libprotobuf-lite.so
      -DPROTOBUF_PROTOC_LIBRARY=$HOME/miniconda/lib/libprotoc.so
      -DPROTOBUF_PROTOC_LIBRARY_DEBUG=$HOME/miniconda/lib/libprotoc.so;
      CFLAGS="-I$HOME/miniconda/include/python$PYTHON_VER" make -j"$(nproc)" install;
      hash -r && make clean;
    fi
  - export PATH=$HOME/caffe2/install/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/caffe2/install/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=$HOME/caffe2/install/lib:$LIBRARY_PATH
  - export CPATH=$HOME/caffe2/install/include:$CPATH
  - export PYTHONPATH=$HOME/caffe2/install
  - ls $HOME/caffe2/install
  - pip install "onnx-caffe2$ONNX_CAFFE2_VERSION"
  - pip install mxnet
  - pip install onnx-mxnet
  - cd $TRAVIS_BUILD_DIR && pip install -e .

script:
  - flake8 .
  - autopep8 -r -d . | tee check_autopep8
  - test ! -s check_autopep8
  - py.test -vvvs -m "not slow" tests